added dot product.vi and delays with Memory node
could not compile due to

Compilation failed due to a Xilinx error.

Details:
ERROR:TclTasksC:process_077: Failed to complete. Please inspect the log
and report files.false
while executing
"process run "Map""
(file "C:\NIFPGA\jobs\AGqcdU2_JOC7Neu\map.tcl" line 7)

ERROR:Place:836 - Not enough free sites available for the components of
the
following type(s).
BLOCKRAM    Number of Components 97    Number of Sites 96
Phase 2.7  Design Feasibility Check (Checksum:b5adb068) REAL time: 1
mins 21 secs
Total REAL time to Placer completion: 1 mins 21 secs
Total CPU  time to Placer completion: 32 secs
ERROR:Pack:1654 - The timing-driven placement phase encountered an
error.
Mapping completed.
See MAP report file "toplevel_gen_map.mrp" for details.
Problem encountered during the packing phase.
Design Summary
--------------
Number of errors   :   2
Number of warnings : 221
Process "Map" failed